import mongoose, { Schema, Document, models, model } from "mongoose";

export interface IProperty extends Document {
	property_id?: string;
	City?: string;
	StateOrProvince?: string;
	ListPrice?: number;
	CurrentPrice?: number;
	Latitude?: number;
	Longitude?: number;
	MLSNumber?: string;
	[key: string]: any;
}

const propertySchema = new Schema<IProperty>(
	{
		property_id: String,
		PropertyClass: String,
		Acres: String,
		AdditionalRooms: String,
		Amenities: String,
		ApproxLivingArea: String,
		BathsFull: String,
		BathsHalf: String,
		BathsTotal: String,
		BedroomDesc: String,
		Bedrooms: String,
		BedsTotal: String,
		BuildingDesc: String,
		BuildingDesign: String,
		CableAvailableYN: String,
		City: String,
		CloseDate: Date,
		ClosePrice: Number,
		CommunityType: String,
		ConditionalDate: String,
		Construction: String,
		Cooling: String,
		CoolingRemarks: String,
		CoolingYN: String,
		CountyOrParish: String,
		CreatedDate: Date,
		CurrentPrice: Number,
		DOM: String,
		DateRented: String,
		Development: String,
		DevelopmentName: String,
		Electric: String,
		Elevator: String,
		Equipment: String,
		ExteriorFeatures: String,
		FencedYardYN: String,
		Flooring: String,
		ForeclosedREOYN: String,
		FullAddress: String,
		FurnishedDesc: String,
		GarageDesc: String,
		GarageSpaces: String,
		GuestHouseDesc: String,
		GulfAccessYN: String,
		Heat: String,
		HeatingRemarks: String,
		HeatingYN: String,
		HighSchool: String,
		InteriorFeatures: String,
		LandLeaseYN: String,
		LandSqFt: String,
		LeasePrice: String,
		LeaseRailYN: String,
		LeaseRateDesc: String,
		ListPrice: Number,
		ListPriceDesc: String,
		LotType: String,
		LotUnit: String,
		matrix_unique_id: String,
		MLS: String,
		MLSAreaMajor: String,
		MLSNumber: String,
		MatrixModifiedDT: Date,
		MiddleSchool: String,
		NumUnitFloor: String,
		NumberDockHighDoors: String,
		NumberOfBays: String,
		NumberOfParcelsLots: String,
		NumberOfSpacesUnits: String,
		NumberofLoadingDoors: String,
		ParcelNumber: String,
		Parking: String,
		Pets: String,
		PetsLimitMaxNumber: String,
		PetsLimitMaxWeight: String,
		PetsLimitOther: String,
		PhotoCount: String,
		PostalCode: String,
		PostalCodePlus4: String,
		PotentialShortSaleYN: String,
		PricePerAcre: String,
		PrivatePoolDesc: String,
		PrivatePoolYN: String,
		PrivateSpaDesc: String,
		PrivateSpaYN: String,
		PropertyAddress: String,
		PropertySearchSlug: String,
		PropertyAddressonInternetYN: String,
		PropertyInformation: String,
		PropertyLocation: String,
		PropertyName: String,
		PropertyType: String,
		PropertyUseType: String,
		Ranges: String,
		RoomCount: String,
		SlipNumber: String,
		SlipType: String,
		StateOrProvince: String,
		Status: String,
		StatusType: String,
		StreetDirPrefix: String,
		StreetDirSuffix: String,
		StreetName: String,
		StreetNumber: String,
		StreetNumberModifier: String,
		StreetSuffix: String,
		SubCondoName: String,
		SubjectPropertySqFt: String,
		Terms: String,
		TotalArea: String,
		TotalBuildingSqFt: String,
		TotalFloors: String,
		Township: String,
		UnitCount: String,
		UnitFloor: String,
		UnitNumber: String,
		UnitsinBuilding: String,
		UnitsinComplex: String,
		UtilitiesAvailable: String,
		Water: String,
		WaterfrontDesc: String,
		WaterfrontYN: String,
		YearBuilt: String,
		DefaultPic: String,
		AllPixDownloaded: String,
		AllPixList: [String],
		PixVerified: String,
		last_image_query: String,
		Longitude: String,
		Latitude: String,
		GeoLocFetched: String,
		other_fields_json: String,
		PostToFbWall: String,
		SendAlerts: String,
		PriceChangeType: String,
		PreviousPptyPrice: String,
		LastChangeDate: Date,
		DateAdded: Date,
		location: {
			type: { type: String, enum: ["Point"], default: "Point" },
			coordinates: { type: [Number], index: "2dsphere" },
		},
	},
	{ timestamps: true, strict: false }
);

const Property =
	models.Property || model<IProperty>("Property", propertySchema);

export default Property;
