name: Deploy Next.js to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install Dependencies
        run: npm install
        env:
          DATABASE_URL: "mysql://dummy:dummy@localhost:3306/dummy"

      - name: Generate Prisma Client
        run: npx prisma generate
        env:
          DATABASE_URL: "mysql://dummy:dummy@localhost:3306/dummy"

      - name: Build the Project
        run: npm run build --force
        env:
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}}
          CLERK_SECRET_KEY: ${{secrets.CLERK_SECRET_KEY}}
          DB_NAME: ${{secrets.DB_NAME}}
          MONGODB_URI: ${{secrets.MONGODB_URI}}
          SERVER_URL: ${{secrets.SERVER_URL}}
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${{secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}}
          NEXT_PUBLIC_WALK_SCORE_API: ${{secrets.NEXT_PUBLIC_WALK_SCORE_API}}
          NEXT_PUBLIC_CLERK_JS_URL: "https://cdn.jsdelivr.net/npm/@clerk/clerk-js@5/dist/clerk.browser.js"

      - name: Prune Dev Dependencies
        run: npm prune --production

      - name: Compress files for fast transfer
        run: tar -czf deploy.tar.gz .next public package.json package-lock.json next.config.mjs node_modules

      - name: Upload Project to VPS via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "deploy.tar.gz" 
          target: "/home/deploy/apps/gulfshoregroup"

      - name: Extract and Restart App on VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /home/deploy/apps/gulfshoregroup
            
            tar -xzf deploy.tar.gz
            rm deploy.tar.gz
            
            pm2 restart nextjs || pm2 start npm --name "nextjs" -- start